BEGIN;

ALTER TABLE app.users FORCE ROW LEVEL SECURITY;
ALTER TABLE app.profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE app.posts FORCE ROW LEVEL SECURITY;
ALTER TABLE app.post_media FORCE ROW LEVEL SECURITY;
ALTER TABLE app.post_likes FORCE ROW LEVEL SECURITY;
ALTER TABLE app.comments FORCE ROW LEVEL SECURITY;
ALTER TABLE app.follows FORCE ROW LEVEL SECURITY;
ALTER TABLE app.follow_requests FORCE ROW LEVEL SECURITY;
ALTER TABLE app.conversations FORCE ROW LEVEL SECURITY;
ALTER TABLE app.conversation_members FORCE ROW LEVEL SECURITY;
ALTER TABLE app.messages FORCE ROW LEVEL SECURITY;
ALTER TABLE app.notifications FORCE ROW LEVEL SECURITY;

COMMIT;
